export const GET_GEOLOCALISATION_REQUEST = 'GET_GEOLOCALISATION_REQUEST';
export const GET_GEOLOCALISATION_SUCCESS = 'GET_GEOLOCALISATION_SUCCESS';
export const GET_GEOLOCALISATION_FAILURE = 'GET_GEOLOCALISATION_FAILURE';
